services:
  - type: web
    name: lex-mente
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lexmente_db
          property: connectionString
      - key: NODE_ENV
        value: production